# -*- coding: utf-8 -*-
"""PRODIGY_GA_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfYi7WGaiuLITFNqH1fQAqY6yt39JAd8
"""

!pip install diffusers transformers accelerate

from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5"
)

import torch
print(torch.cuda.is_available())

pipe = pipe.to("cuda")

prompt = "A futuristic city with flying cars at sunset"

image = pipe(prompt).images[0]

image